name: Build AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install

      - name: Increase Node memory
        run: echo "NODE_OPTIONS=--max-old-space-size=4096" >> $GITHUB_ENV

      - run: npx expo prebuild --platform android --non-interactive --clean

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Test JS bundle directly
        run: npx react-native bundle \
              --platform android \
              --dev false \
              --entry-file index.js \
              --bundle-output test.bundle \
              --assets-dest test

      - name: make AAB  
        run: cd android && ./gradlew bundleRelease --no-daemon --max-workers=2 --debug



      - name: Sign AAB
        run: |
          keytool -importkeystore -srckeystore ${{ secrets.KEYSTORE }} \
          -destkeystore ${{ secrets.DEST_KEYSTORE }} \
          -srcstoretype JKS -deststoretype JKS \
          -srcalias aliasName -destalias aliasName \
          -srcstorepass ${{ secrets.KEYSTORE_PASSWORD }} -deststorepass ${{ secrets.KEYSTORE_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release.aab